name: beat-pd-team-dbmi
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python==3.7
  - snakemake==5.19.3
  - tsfresh==0.14.1
  - numpy==1.18.1
  - pandas==1.0.3
  - seaborn==0.10.0
  - scipy==1.4.1
  - tqdm==4.44.1
  - matplotlib==3.1.3
  - dask-jobqueue==0.7.0
  - distributed==2.14.0
  - scikit-learn==0.22.1
  - statsmodels==0.11.0
  - dask==2.14.0
  - dask-ml==1.4.0
  - dill==0.3.2